# This GitHub Action pulls the dependency container from https://github.com/cisco/mindmeld/tree/master/docker_containers/mindmeld_dep_docker,
#   builds it, and publishes it to GitHub Container Registry

name: Docker Build
on:
  schedule:
    - cron:  '0 */24 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Checkout Mindmeld Repo
        uses: actions/checkout@v3
        with:
          name: cisco/mindmeld
      
      - name: Generate Image Name
        id: name
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ env.GITHUB_REPOSITORY }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ghcr.io/${{ steps.name.outputs.lowercase }}:latest