# This GitHub Action pulls the dependency container from https://github.com/cisco/mindmeld/tree/master/docker_containers/mindmeld_dep_docker,
#   builds it, and publishes it to GitHub Container Registry

name: Docker Build
on:
  push:
    branches:
      - master
  schedule:
      - cron:  '0 */24 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Checkout Mindmeld Repo
        uses: actions/checkout@v4
        with:
          repository: cisco/mindmeld
          path: ./mindmeld
      
      - name: Generate Image Name
        id: name
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository }}

      - name: Get Short SHA Of Last Mindmeld Commit
        id: short
        working-directory: ./mindmeld
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Get Long SHA Of Last Mindmeld Commit
        id: long
        working-directory: ./mindmeld
        run: echo "::set-output name=sha_long::$(git rev-parse HEAD)"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./mindmeld/docker_containers/mindmeld_dep_docker
          push: true
          tags: |
            ghcr.io/${{ steps.name.outputs.lowercase }}:latest
            ghcr.io/${{ steps.name.outputs.lowercase }}:${{ steps.short.outputs.sha_short }}
            ghcr.io/${{ steps.name.outputs.lowercase }}:${{ steps.long.outputs.sha_long }}